name: Libaluna
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Install RClone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone help
      - name: Requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel && python -m pip install lbry-libtorrent && apt install python3-libtorrent
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Cd Into Repo
        run: |
          cd ${{ github.workspace }}
      - name: Downloading config file
        run: |
          wget -qq ${{ secrets.Rclone }} -O rclone.conf
      - name: Downloading link file
        run: |
          wget -qq https://gist.github.com/BlackFoxy616/97e8a848878c7edde0e7653aacab95af/raw/846e94445577b6951e894b05657abb9dff59559e/links(tor).txt -O links.txt
